export const MAIN_BLUE = '#4169E1'
export const LIGHT_BLUE = '#1E90FF'
export const ACCENT_BLUE = '#0000FF'
export const LIGHT_GREY = '#C0C0C0'
export const DARK_GREY = '#A9A9A9'
export const WHITE = '#FFFFFF'
export const BLACK = '#202020'
